BASE = ../../..

NAME = zlib_unit

SRCS = main.cc zlib.cc

include $(BASE)/import/googletest/googletest/make.mk
include $(BASE)/import/zlib/make.mk
include $(BASE)/util/make.mk

include $(BASE)/make/app.mk
